// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional

// COPY AND PASTE THE CONFIG GENERATED BY FIREBASE HERE
const firebaseConfig = {
    apiKey: "",
    authDomain: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: "9",
    measurementId: ""
};

// IMPORTANT ADD THIS LINE
export default firebaseConfig;